config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flats_path
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flats_path
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Edit this Flat!</h1>
<div class="form">
  <%= simple_form_for(@flat) do |f| %>
    <div class="col-6" >
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guests, collection: [1, 2, 3, 4, 5] %>
      <%= f.submit class:"btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1>All Our Flats</h1>
</div>
<div class="row">
  <% @flats.each do |flat| %>
    <div class="col-4">
      <div class="card">
        <p><%= image_tag flat.picture, class:"image" %></p>
        <h3><%= link_to flat.name, flat_path(flat) %></h3>
        <p><%= flat.address %></p>
        <p><%= flat.description %></p>
        <p><i class="fas fa-euro-sign"></i> <%= flat.price_per_night %> - <i class="fas fa-user-friends"></i> <%= flat.number_of_guests %></p>
        <div class="options">
          <%= link_to "See More", flat_path(flat) %>
          <%= link_to "Edit this Flat", edit_flat_path(flat) %>
        </i><%= link_to flat_path(flat), method: :delete, data: { confirm: "Are you sure you want to delete this flat?" } do %><i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>
<%= link_to "Add a new flat", new_flat_path(@flat), class:"btn btn-warning" %>

app/views/flats/new.html.erb
<div class="form">
  <%= simple_form_for(@flat) do |f| %>
    <div class="col-6" >
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guests %>
      <%= f.submit class:"btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="card-big">
  <p><%= image_tag @flat.picture, class:"image" %></p>
  <h3><%= @flat.name %></h3>
  <p><%= @flat.address %></p>
  <p><%= @flat.description %></p>
  <p>$<%= @flat.price_per_night %> - <%= @flat.number_of_guests %> Guests</p>
</div>
<%= link_to "Back to flats", flats_path, class:"link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= yield %>
  </body>
</html>